# Keep the base file minimal and environment-agnostic.
# Everything connection- or environment-specific goes into profile files
# (application-dev.yml, application-prod.yml) or env vars.

spring:
  datasource:
    # Datasource URL provided via environment variables.  Use the DB_HOST,
    # DB_PORT and DB_NAME variables to assemble a sensible default if
    # DATASOURCE_URL is not explicitly set.  The default points to a
    # PostgreSQL instance on localhost.  See README for details on
    # configuring these values for containerised or managed databases.
    url: ${DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:agentdb}}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${DATASOURCE_USERNAME:agent}
    password: ${DATASOURCE_PASSWORD:agent}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/c07f229d-ff5a-4a54-9be4-1e37e3783cdd/v2.0

  ai:
    chat:
      memory:
        repository:
          jdbc:
            # In prod we recommend managing schema via migrations; dev overrides this.
            initialize-schema: always
    openai:
      api-key: ${OPENAI_API_KEY}
#  cloud:
#    azure:
#      keyvault:
#        secret:
#          property-sources:
#            - name: key-vault-property-source
#              endpoint: https://<your-vault>.vault.azure.net/
management:
  endpoints:
    web:
      # In base, expose minimal set; dev will widen this.
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

app:
  cors:
    allowed-origins: http://localhost:8080,http://localhost:3000,http://localhost:5173
