# Keep the base file minimal and environment-agnostic.
# Everything connection- or environment-specific goes into profile files
# (application-dev.yml, application-prod.yml) or env vars.

spring:
  ai:
    chat:
      memory:
        repository:
          jdbc:
            # In prod we recommend managing schema via migrations; dev overrides this.
            initialize-schema: never

management:
  endpoints:
    web:
      # In base, expose minimal set; dev will widen this.
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
