-- NOTE: This schema is only included because Spring AI was not automatically
--       initializing the SPRING_AI_CHAT_MEMORY table in the H2 dev environment.
--       In production, this is handled automatically by Spring AI when using a
--       supported database, so this file is only for local development/testing.
CREATE TABLE IF NOT EXISTS SPRING_AI_CHAT_MEMORY (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     conversation_id VARCHAR(255) NOT NULL,
    content CLOB NOT NULL,
    type VARCHAR(50) NOT NULL,
    "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE INDEX IF NOT EXISTS idx_spring_ai_chat_memory_conv
    ON SPRING_AI_CHAT_MEMORY (conversation_id);
